
learning_rate: 0.0005
batch_size: 8             
num_epochs: 30
early_stopping_patience: 4


train_dir: "C:/Users/parkminhyuk/Downloads/DeepfakeDetector-main/open/data/train"
val_dir: "C:/Users/parkminhyuk/Downloads/DeepfakeDetector-main/open/data/validation"


scheduler_factor: 0.5
scheduler_patience: 3
monitor_metric: "val_loss"
log_every_n_steps: 1
save_top_k: 1